#server.port=8080

#Spring Data JPA
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5433/kelevo_market_db
spring.datasource.username=user
spring.datasource.password=secret